#  Support Vector Machine
# Classifying the Stars as Giants or Dwarves

### Importing the libraries

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Data Handling

### Importing the Dataset

In [3]:
dataset = pd.read_csv('star.csv')


In [6]:
dataset.head()

Vmag    Plx  e_Plx    B-V SpType       Amag  TargetClass
0  5.99  13.73   0.58  1.318  K5III  16.678352            0
1  8.70   2.31   1.29 -0.045   B1II  15.518060            0
2  5.77   5.50   1.03  0.855  G5III  14.471813            0
3  6.72   5.26   0.74 -0.015    B7V  15.324928            1
4  8.76  13.44   1.16  0.584    G0V  19.401997            1

### Preprcossing the Data

In [7]:
# Removing the String Column and convert to the numerical form
dataset['SpType'].value_counts() #Check the Spectral Types

K0III          293
K1III          200
K2III          156
G8III          135
F5V            125
              ... 
B9.5IV           1
B0Ibp            1
M0V              1
B1Vv SB          1
M0/M1IIICNp      1
Name: SpType, Length: 584, dtype: int64

In [18]:
def codes_modif(columnname, dataset):
    value_counts = dataset[columnname].value_counts()
    replacers = {value: index for index, value in enumerate(value_counts.index)}
    dataset[columnname] = dataset[columnname].map(replacers)
    return dataset

dataset = codes_modif("SpType", dataset)

In [19]:
dataset.head()

Vmag    Plx  e_Plx    B-V  SpType       Amag  TargetClass
0  5.99  13.73   0.58  1.318      14  16.678352            0
1  8.70   2.31   1.29 -0.045     163  15.518060            0
2  5.77   5.50   1.03  0.855      34  14.471813            0
3  6.72   5.26   0.74 -0.015     111  15.324928            1
4  8.76  13.44   1.16  0.584      13  19.401997            1

In [20]:
dataset['SpType'].value_counts()

0      293
1      200
2      156
3      135
4      125
      ... 
579      1
580      1
581      1
582      1
583      1
Name: SpType, Length: 584, dtype: int64

In [21]:
X = dataset.iloc[:, :-1].values # Defining the X division
y = dataset.iloc[:, -1].values #Defining the y division, which is the result column

## Splitting into Training and Testing dataset

In [22]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

In [23]:
print(X_train)

[[  5.59       5.19       0.77       1.185      1.        14.165836]
 [  7.9        2.77       0.89       1.157      1.        15.1124  ]
 [  8.71      13.15       0.85       0.614     91.        19.30463 ]
 ...
 [  9.19       7.22       1.27       0.596      9.        18.482685]
 [  9.09       2.7        1.95       0.9        0.        16.246819]
 [  7.79       0.82       0.94       0.883    372.        12.359069]]


In [25]:
print(y_train)

[0 0 1 ... 1 0 0]


In [26]:
print(X_test)

[[  9.02        2.37        1.23        0.958       3.         15.893742 ]
 [  9.26       12.39        1.45        0.589      21.         19.725357 ]
 [  6.41        2.17        0.63        0.998     261.         13.0922985]
 ...
 [  8.94        1.56        1.          1.419      11.         14.9056225]
 [ 10.23        4.02        1.7         0.417      10.         18.25113  ]
 [  7.88       14.56        1.06        0.447       6.         18.695807 ]]


In [27]:
print(y_test)

[0 1 0 1 1 0 1 0 1 0 1 0 0 1 0 1 0 0 1 0 0 0 1 0 1 1 0 1 0 0 0 0 1 0 0 1 1
 1 0 0 1 0 1 1 1 1 0 0 0 0 0 1 0 0 1 1 0 1 1 1 0 0 0 1 1 0 1 0 0 1 1 0 1 0
 0 0 1 0 1 0 0 1 1 1 0 1 1 0 0 1 1 0 0 1 0 0 1 0 0 1 1 1 1 1 1 0 1 1 0 0 1
 0 1 0 0 0 0 1 1 0 1 1 0 1 1 0 1 1 0 0 0 1 1 1 0 1 0 1 1 0 1 0 1 0 1 1 1 0
 0 1 1 0 1 0 1 1 1 1 0 1 0 1 1 1 1 0 0 0 1 0 1 0 1 0 0 1 0 1 1 1 0 1 0 0 1
 1 0 1 1 0 0 0 1 0 0 0 1 1 0 0 1 1 0 1 0 1 0 0 0 0 0 0 1 0 0 0 0 0 1 1 1 0
 0 1 0 1 0 0 0 0 1 0 1 1 1 0 0 0 0 1 1 1 1 1 1 0 1 1 1 1 0 1 1 1 1 0 1 0 0
 1 1 0 1 0 0 0 0 1 1 0 0 1 0 1 0 1 0 0 1 1 0 1 0 1 0 0 0 0 0 0 0 1 1 0 1 1
 1 0 1 0 1 0 1 1 0 1 0 1 0 0 0 0 0 1 1 1 1 0 1 1 1 1 0 0 0 0 1 0 0 0 1 0 1
 1 0 0 1 1 0 0 1 0 1 0 0 1 1 1 1 1 1 0 1 1 0 0 0 0 0 1 1 1 0 0 0 1 1 1 1 0
 0 1 0 0 1 0 0 0 0 1 0 0 1 1 0 0 1 1 0 0 0 0 0 0 1 1 1 0 1 0 0 1 0 1 0 0 0
 0 1 0 1 1 0 0 1 1 0 0 1 1 0 1 0 0 1 1 1 0 1 1 1 0 0 1 0 1 0 1 0 0 0 0 0 1
 1 0 0 1 0 1 0 0 1 1 0 0 0 0 0 0 1 0 0 0 1 0 1 0 0 0 0 0 1 1 0 0 0 1 1 0 0
 1 1 0 0 0 1 0 1 1 0 0 0 

## Feature Scaling

In [28]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

## Training the SVM Model on the Training Set

In [30]:
from sklearn.svm import SVC
classifier = SVC(kernel = 'linear', random_state = 0)
classifier.fit(X_train, y_train)

SVC(kernel='linear', random_state=0)

In [37]:
ans=classifier.predict(sc.transform([[5.99,13.73,0.58,1.318,14,16.678352]]))

if ans==0:
  print("The given star is Dwarf star")
else:
  print("The given star is Giant star")

The given Planet is Dwarf Planet
